"""Generate the four information-flow figures as TikZ sources.

Run ``./build.sh`` (or ``python3 make_figures.py``) from this directory. Edit
this script, not the generated ``.tex`` files. The figures use layout A:
L1 prelude, L2 T-buffer, L3-L6 core, L7 T-source, L8 coda.

Two views of the same models:
- layer-wise: every layer L1-L8 drawn;
- functional: one block per role (the four core layers as one taller block).

Training figures pair each position's pass i-1 and pass i columns, so a depth
read (same position) is a short arrow and a temporal read (next position) is
a long one. Layers a pass does not run are dashed; the prelude runs once per
trajectory and is one box shared by both passes.
"""
from pathlib import Path

POSITIONS = ['$t{-}1$', '$t$', '$t{+}1$']
PANELS = {'tl': (2.35, 7.35), 'tr': (13.00, 7.35), 'bl': (2.35, -1.05), 'br': (13.00, -1.05)}


# ---------------------------------------------------------------------------
# Views: rows from bottom to top. role in prelude/buffer/core/core_out/source/coda.

def row(name, y, role, label=None, height=None):
    return dict(name=name, y=y, role=role, label=label, height=height)


LAYER_VIEW = dict(
    unit='layer',
    rows=[row('r1', 0.80, 'prelude', 'L1 prelude'), row('r2', 1.55, 'buffer', 'L2 T-buffer'),
          row('r3', 2.30, 'core'), row('r4', 2.85, 'core'), row('r5', 3.40, 'core'),
          row('r6', 3.95, 'core_out'), row('r7', 4.50, 'source', 'L7 T-source'),
          row('r8', 5.05, 'coda', 'L8 coda')],
    core_brace=('r3', 'r6', 'L3--L6\\\\core'),
    vanilla=('rows', 'L1--L8\\\\blocks'),
    cell_h='0.32cm',
)
FUNCTIONAL_VIEW = dict(
    unit='block',
    rows=[row('b1', 0.80, 'prelude', 'prelude (L1)'), row('b2', 1.70, 'buffer', 'T-buffer (L2)'),
          row('b3', 2.95, 'core_out', 'core (L3--L6)', height=0.95), row('b4', 4.20, 'source', 'T-source (L7)'),
          row('b5', 5.05, 'coda', 'coda (L8)')],
    core_brace=None,
    vanilla=('block', 'L1--L8'),
    cell_h='0.38cm',
)


def injection_y(view, below_role, above_role):
    rows = {r['role']: r for r in view['rows']}
    lower = next(r for r in view['rows'] if r['role'] == below_role)
    upper = next(r for r in view['rows'] if r['role'] in above_role)
    top = lower['y'] + 0.16 if not lower['height'] else lower['y'] + lower['height'] / 2
    bottom = upper['y'] - (upper['height'] / 2 if upper['height'] else 0.16)
    return (top + bottom) / 2


def t_y(view):
    return injection_y(view, 'prelude', ('buffer',))


def d_y(view):
    return injection_y(view, 'buffer', ('core', 'core_out'))


# ---------------------------------------------------------------------------
# TikZ helpers

def preamble(cell_w, cell_h):
    return (
        '% Generated by make_figures.py; edit that script instead of this file.\n'
        '\\documentclass[tikz,border=7pt]{standalone}\n'
        '\\usepackage{amsmath}\n'
        '\\usetikzlibrary{arrows.meta,calc,positioning,decorations.pathreplacing}\n'
        f'\\def\\figcellw{{{cell_w}}}\\def\\figcellh{{{cell_h}}}\n'
        '\\input{figure_style}\n\n'
        '\\begin{document}\n\\begin{tikzpicture}[x=1cm,y=1cm]\n'
    )


def scaffold(title):
    return f'''
\\node[font=\\bfseries\\LARGE] at (11.9,17.30) {{{title}}};
\\node[header, minimum width=10.35cm, minimum height=0.85cm, font=\\bfseries\\large] at (7.525,15.945) {{Depth recurrence OFF}};
\\node[header, minimum width=10.35cm, minimum height=0.85cm, font=\\bfseries\\large] at (18.175,15.945) {{Depth recurrence ON}};
\\node[sideheader, minimum width=8.05cm, minimum height=0.85cm, rotate=90, font=\\bfseries\\large] at (1.805,11.38) {{Temporal recurrence OFF}};
\\node[sideheader, minimum width=8.05cm, minimum height=0.85cm, rotate=90, font=\\bfseries\\large] at (1.805,2.98) {{Temporal recurrence ON}};
'''


def panel_open(key, title, caption):
    x, y = PANELS[key]
    return (f'\n% ---------------- {title}\n'
            f'\\begin{{scope}}[shift={{({x},{y})}}]\n'
            '  \\draw[panel] (0,0) rectangle (10.35,8.05);\n'
            f'  \\node[font=\\bfseries\\large] at (5.175,7.62) {{{title}}};\n'
            f'  \\node[descbox, text width=9.6cm] at (5.175,6.92) {{{caption}}};\n')


def node(style, name, x, y, extra=''):
    return f'  \\node[{style}{extra}] ({name}) at ({x:.3f},{y:.3f}) {{}};\n'


def cell(style, name, x, r, extra=''):
    size = f', minimum height={r["height"]}cm' if r['height'] else ''
    return node(style, name, x, r['y'], size + extra)


def arrow(style, a, b):
    return f'  \\draw[{style}] ({a}.north) -- ({b}.south);\n'


def row_labels(view, recurrent, x=2.30):
    rows = view['rows']
    if not recurrent:
        kind, text = view['vanilla']
        if kind == 'rows':
            return (f'  \\draw[decorate,decoration={{brace,amplitude=4pt}}] ({x},{rows[0]["y"] - 0.16}) -- '
                    f'({x},{rows[-1]["y"] + 0.16}) node[brace label] {{{text}}};\n')
        return ''
    out = []
    for r in rows:
        if r['label']:
            out.append(f'  \\node[anchor=east, font=\\footnotesize] at ({x + 0.12},{r["y"]}) {{{r["label"]}}};\n')
    if view['core_brace']:
        low, high, text = view['core_brace']
        y0 = next(r['y'] for r in rows if r['name'] == low) - 0.16
        y1 = next(r['y'] for r in rows if r['name'] == high) + 0.16
        out.append(f'  \\draw[decorate,decoration={{brace,amplitude=4pt}}] ({x},{y0}) -- ({x},{y1})'
                   f' node[brace label] {{{text}}};\n')
    return ''.join(out)


def vanilla_column(view, key, c, x, style, flow):
    """One ordinary-transformer column: every row, or one block for the functional view."""
    kind, text = view['vanilla']
    rows = view['rows']
    if kind == 'block':
        low, high = rows[0]['y'] - 0.19, rows[-1]['y'] + 0.19
        return (f'  \\node[{style}, minimum height={high - low:.2f}cm, minimum width=1.15cm, font=\\footnotesize] ({key}c{c}) '
                f'at ({x:.3f},{(low + high) / 2:.3f}) {{{text}}};\n')
    s = ''.join(cell(style, f'{key}c{c}{r["name"]}', x, r) for r in rows)
    s += ''.join(arrow(flow, f'{key}c{c}{a["name"]}', f'{key}c{c}{b["name"]}') for a, b in zip(rows, rows[1:]))
    return s


def legend(rows, height=1.45):
    """rows: lists of (kind, style, text) laid out left to right."""
    out = ['\n% ---------------- Legend\n', '\\begin{scope}[shift={(2.35,-2.85)}]\n',
           f'  \\draw[panel] (0,0) rectangle (21.00,{height});\n']
    for r, items in enumerate(rows):
        y = height - 0.42 - r * 0.55
        x = 0.6
        for kind, style, text in items:
            if kind == 'box':
                size = '' if 'minimum width' in style else ', minimum width=0.70cm'
                out.append(f'  \\node[{style}{size}] at ({x + 0.35:.2f},{y:.2f}) {{}};\n')
                out.append(f'  \\node[legendtext] at ({x + 0.85:.2f},{y:.2f}) {{{text}}};\n')
            elif kind == 'arrow':
                out.append(f'  \\draw[{style}] ({x:.2f},{y:.2f}) -- ({x + 0.75:.2f},{y:.2f});\n')
                out.append(f'  \\node[legendtext] at ({x + 0.85:.2f},{y:.2f}) {{{text}}};\n')
            elif kind == 'inject':
                arrow_style, circle = style
                out.append(f'  \\draw[{arrow_style}] ({x:.2f},{y:.2f}) -- ({x + 0.55:.2f},{y:.2f});\n')
                out.append(f'  \\node[{circle}] at ({x + 0.75:.2f},{y:.2f}) {{{circle[-1]}}};\n')
                out.append(f'  \\node[legendtext] at ({x + 1.0:.2f},{y:.2f}) {{{text}}};\n')
            x += 4.95
    out.append('\\end{scope}\n')
    return ''.join(out)


def top_label_y(view):
    return view['rows'][-1]['y'] + 0.57


# ---------------------------------------------------------------------------
# Training time

PREV_X = [2.95, 5.20, 7.45]
PAIR = 0.95  # distance between a position's pass i-1 and pass i columns


def training_panel(view, key, title, caption, depth, temporal):
    s = panel_open(key, title, caption)
    recurrent = depth or temporal
    s += row_labels(view, recurrent)
    rows = view['rows']
    header_y = top_label_y(view)
    if not recurrent:
        s += f'  \\node[font=\\bfseries\\footnotesize] at (5.60,{header_y:.2f}) {{single pass}};\n'
        for c, x in enumerate([3.70, 5.60, 7.50]):
            s += vanilla_column(view, key, c, x, 'active', 'flow')
            s += f'  \\node[font=\\footnotesize] at ({x},0.28) {{{POSITIONS[c]}}};\n'
        return s + '\\end{scope}\n'
    s += f'  \\node[anchor=east, font=\\footnotesize, text=black!60] at (2.42,{header_y:.2f}) {{pass}};\n'
    upper = rows[1:]  # everything above the shared prelude
    by_role = {r['role']: r for r in rows}
    core_out = by_role['core_out']
    source = by_role['source']
    later = []  # state arrows and injection points drawn on top
    for c, px in enumerate(PREV_X):
        cx = px + PAIR
        p, q = f'{key}p{c}', f'{key}q{c}'
        s += f'  \\node[font=\\footnotesize, text=black!60] at ({px},{header_y:.2f}) {{$i{{-}}1$}};\n'
        s += f'  \\node[font=\\bfseries\\footnotesize] at ({cx},{header_y:.2f}) {{$i$}};\n'
        s += node('active', f'{key}pre{c}', (px + cx) / 2, rows[0]['y'], f', minimum width={PAIR + 0.62}cm')
        # Pass i-1 (non-final): buffer and core run; the source only for a temporal
        # write; the coda never.
        last_run = None
        for r in upper:
            style = 'ghost'
            if r['role'] == 'core_out' and depth:
                style = 'depthmark'
            if r['role'] == 'source':
                style = 'tempmark' if temporal else 'notrun'
            if r['role'] == 'coda':
                style = 'notrun'
            s += cell(style, f'{p}{r["name"]}', px, r)
            if style != 'notrun':
                if last_run is None:
                    s += f'  \\draw[ghostflow] ({key}pre{c}.north -| {p}{r["name"]}) -- ({p}{r["name"]}.south);\n'
                else:
                    s += arrow('ghostflow', f'{p}{last_run}', f'{p}{r["name"]}')
                last_run = r['name']
        # Pass i (final): everything above the prelude runs.
        for r in upper:
            s += cell('active', f'{q}{r["name"]}', cx, r)
        s += f'  \\draw[flow] ({key}pre{c}.north -| {q}{upper[0]["name"]}) -- ({q}{upper[0]["name"]}.south);\n'
        for a, b in zip(upper, upper[1:]):
            s += arrow('flow', f'{q}{a["name"]}', f'{q}{b["name"]}')
        s += f'  \\node[font=\\footnotesize] at ({(px + cx) / 2},0.28) {{{POSITIONS[c]}}};\n'
        if depth:
            later.append(f'  \\draw[dread, rounded corners=3pt] ({p}{core_out["name"]}.east) -- ++(0.165,0) '
                         f'|- ({cx - 0.19:.3f},{d_y(view):.3f});\n')
            later.append(f'  \\node[injectD] at ({cx:.3f},{d_y(view):.3f}) {{D}};\n')
        if temporal and c > 0:
            src = f'{key}p{c - 1}{source["name"]}'
            later.append(f'  \\draw[tread] ({src}.east) .. controls +(0.9,-0.1) and +(-0.55,0.9) .. '
                         f'({cx - 0.13:.3f},{t_y(view) + 0.13:.3f});\n')
            later.append(f'  \\node[injectT] at ({cx:.3f},{t_y(view):.3f}) {{T}};\n')
    return s + ''.join(later) + '\\end{scope}\n'


def training_figure(view, subtitle):
    unit = view['unit']
    core = 'core output (L6)' if unit == 'layer' else 'core output'
    s = preamble('0.62cm', view['cell_h']) + scaffold(f'Training-time information flows{subtitle}')
    s += training_panel(view, 'tl', 'Vanilla transformer',
                        'One pass through L1--L8 at every position (embedding and head not shown).', False, False)
    s += training_panel(view, 'tr', 'Depth-recurrent / looped LM',
                        f'Pass $i{{-}}1$ writes the {core} as depth state; pass $i$ reads it at the '
                        'same position, just before the core.', True, False)
    s += training_panel(view, 'bl', 'Temporally recurrent',
                        'Pass $i{-}1$ writes the T-source output (L7) as temporal state; pass $i$ reads it one '
                        'position later, just after the prelude.', False, True)
    s += training_panel(view, 'br', 'Depth + temporal hybrid',
                        'Both at once: depth state stays at its position (short orange arrows), temporal state '
                        'moves one position forward (long purple arrows).', True, True)
    s += legend([
        [('box', 'ghost', f'pass $i{{-}}1$ {unit}'), ('box', 'active', f'pass $i$ {unit}'),
         ('box', 'notrun', 'not run on this pass'), ('box', 'active, minimum width=1.0cm', 'prelude: runs once')],
        [('box', 'depthmark', 'writes depth state'), ('box', 'tempmark', 'writes temporal state'),
         ('inject', ('dread', 'injectD'), 'depth read (same position)'),
         ('inject', ('tread', 'injectT'), 'temporal read (next position)')],
    ])
    return s + '\\end{tikzpicture}\n\\end{document}\n'


# ---------------------------------------------------------------------------
# Inference time

TOKEN_X = [3.35, 6.55]


def inference_panel(view, key, title, caption, depth, temporal):
    s = panel_open(key, title, caption)
    s += row_labels(view, depth or temporal)
    rows = view['rows']
    header_y = top_label_y(view)
    s += f'  \\node[font=\\bfseries\\footnotesize, text=black!60] at ({TOKEN_X[0]},{header_y:.2f}) {{token $t{{-}}1$}};\n'
    s += f'  \\node[font=\\bfseries\\footnotesize] at ({TOKEN_X[1]},{header_y:.2f}) {{token $t$}};\n'
    if not (depth or temporal):
        s += vanilla_column(view, key, 0, TOKEN_X[0], 'ghost', 'ghostflow')
        s += vanilla_column(view, key, 1, TOKEN_X[1], 'active', 'flow')
        return s + '\\end{scope}\n'
    by_role = {r['role']: r for r in rows}
    later = []
    for c, x in enumerate(TOKEN_X):
        name, current = f'{key}k{c}', c == 1
        for r in rows:
            style = 'active' if current else 'ghost'
            if r['role'] == 'core_out' and depth:
                style = 'depthmark' if current else 'ghostdepth'
            if r['role'] == 'source' and temporal:
                style = 'tempmark' if current else 'ghosttemp'
            s += cell(style, f'{name}{r["name"]}', x, r)
        flow = 'flow' if current else 'ghostflow'
        for a, b in zip(rows, rows[1:]):
            s += arrow(flow, f'{name}{a["name"]}', f'{name}{b["name"]}')
    q, p = f'{key}k1', f'{key}k0'
    core_out, source, coda = by_role['core_out'], by_role['source'], by_role['coda']
    if depth:
        loop_mid = (core_out['y'] + d_y(view)) / 2
        later.append(f'  \\draw[dread, rounded corners=4pt] ({q}{core_out["name"]}.east) -- ++(0.45,0) '
                     f'|- ({TOKEN_X[1] + 0.19:.3f},{d_y(view):.3f});\n')
        later.append(f'  \\node[font=\\footnotesize, text=depthdraw, anchor=west] at ({TOKEN_X[1] + 1.10:.3f},{loop_mid:.3f})'
                     ' {repeat $J$ times};\n')
        later.append(f'  \\node[injectD] at ({TOKEN_X[1]:.3f},{d_y(view):.3f}) {{D}};\n')
    if temporal:
        later.append(f'  \\draw[tread] ({p}{source["name"]}.east) .. controls +(1.4,-0.2) and +(-1.2,1.2) .. '
                     f'({TOKEN_X[1] - 0.13:.3f},{t_y(view) + 0.13:.3f});\n')
        later.append(f'  \\node[injectT] at ({TOKEN_X[1]:.3f},{t_y(view):.3f}) {{T}};\n')
        later.append(f'  \\draw[tread] ({q}{source["name"]}.east) .. controls +(0.7,0) and +(-0.5,0) .. '
                     f'({TOKEN_X[1] + 1.55:.3f},{coda["y"] + 0.35:.3f})'
                     ' node[anchor=west, font=\\footnotesize, text=tempdraw] {to token $t{+}1$};\n')
    return s + ''.join(later) + '\\end{scope}\n'


def inference_figure(view, subtitle):
    unit = view['unit']
    s = preamble('0.90cm' if unit == 'layer' else '1.15cm', view['cell_h'])
    s += scaffold(f'Inference-time information flows{subtitle}')
    s += inference_panel(view, 'tl', 'Vanilla transformer',
                         'Each token runs L1--L8 once; no state is carried between tokens.', False, False)
    s += inference_panel(view, 'tr', 'Depth-recurrent / looped LM',
                         'The core (L3--L6) runs $J$ times per token; its output re-enters before the core. '
                         'Depth state is discarded at the next token.', True, False)
    s += inference_panel(view, 'bl', 'Temporally recurrent',
                         'Token $t{-}1$\'s T-source output (L7) is read by token $t$ after the prelude, so the chain '
                         'runs through every earlier token.', False, True)
    s += inference_panel(view, 'br', 'Depth + temporal hybrid',
                         'Temporal state crosses tokens; depth state loops only within the current token.', True, True)
    s += legend([
        [('box', 'ghost', f'token $t{{-}}1$ {unit}'), ('box', 'active', f'token $t$ {unit}'),
         ('box', 'depthmark', 'writes depth state'), ('box', 'tempmark', 'writes temporal state')],
        [('arrow', 'flow', 'within-token flow'), ('inject', ('dread', 'injectD'), 'depth read (loop)'),
         ('inject', ('tread', 'injectT'), 'temporal read'), ('arrow', 'tread', 'state passed to next token')],
    ])
    return s + '\\end{tikzpicture}\n\\end{document}\n'


if __name__ == '__main__':
    here = Path(__file__).parent
    outputs = {
        'training_time_layer_wise.tex': training_figure(LAYER_VIEW, ''),
        'inference_time_layer_wise.tex': inference_figure(LAYER_VIEW, ''),
        'training_time_functional.tex': training_figure(FUNCTIONAL_VIEW, ' (functional blocks)'),
        'inference_time_functional.tex': inference_figure(FUNCTIONAL_VIEW, ' (functional blocks)'),
    }
    for name, text in outputs.items():
        (here / name).write_text(text)
    print('wrote', ', '.join(outputs))
