# Bounded local check; deliberately not a serious-run comparison.
architecture = 'recurrent'
out_dir = 'experiments/smoke/results/recurrent_mps'
dataset = 'chess_long_v1'
n_layer = 8
n_head = 8
n_embd = 512
n_prelude = 1
n_buffer = 1
n_core = 4
n_source = 1
n_coda = 1
block_size = 1023
batch_size = 2
gradient_accumulation_steps = 4
recurrence_support = [0, 1, 3]
recurrence_probabilities = [[.10, .12, .04], [.12, .26, .08], [.04, .08, .16]]
eval_u_t = 3
eval_u_d = 3
max_iters = 100
warmup_iters = 10
lr_decay_iters = 100
eval_interval = 25
eval_iters = 4
log_interval = 10
compile = False
device = 'mps'
dtype = 'float32'
num_threads = 4
