# Small executable contract check; not a scientific architecture comparison.
architecture = 'recurrent'
out_dir = 'out-recurrent-smoke'
dataset = 'smoke_real'
n_layer = 4
n_head = 2
n_embd = 32
n_prelude = 1
n_core = 1
n_coda = 1
block_size = 32
batch_size = 2
gradient_accumulation_steps = 2
recurrence_support = [0, 1, 3]
recurrence_probabilities = [[0.10, 0.12, 0.04], [0.12, 0.26, 0.08], [0.04, 0.08, 0.16]]
recurrence_seed = 1729
eval_u_t = 3
eval_u_d = 3
max_iters = 12
warmup_iters = 0
lr_decay_iters = 12
eval_interval = 6
eval_iters = 2
log_interval = 2
compile = False
device = 'cpu'
dtype = 'float32'
num_threads = 2
